id: opecha:P000362
initial_creation_type: ocr
source_metadata:
  id: bdr:W29016
  title: དབུ་མའི་སྤྱི་དོན་སྐལ་བཟང་མགུལ་རྒྱན་གྱི་དགོངས་དོན་གསལ་བར་བྱེད་པའི་ཡང་གསལ་སྒྲོན་མེ།
  volume:
    52750a7f38e447fa9610ac966132f2de:
      image_group_id: I1PD28110
      title: Volume 1 of dbu ma'i spyi don skal bzang mgul rgyan gyi dgongs don gsal
        bar byed pa'i yang gsal sgron me
      volume_number: 1
      total_pages: 322
  author: ''
ebook_metadata:
  title: དབུ་མའི་སྤྱི་དོན་སྐལ་བཟང་མགུལ་རྒྱན་གྱི་དགོངས་དོན་གསལ་བར་བྱེད་པའི་ཡང་གསལ་སྒྲོན་མེ།
  author: ''
  sku: P000362
  cover: cover.jpg
  layers:
  - pagination
